### ISSUE TITLE
calendar-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/calendar-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Being extremely efficient with their time somehow. Maybe because of their great app.

**Comment by toddy** [comment]
When I see it correct the project in launchpad should be running for the translation tasks. There are many bugs in the launchpad project. Should the bugs fix here or in launchpad? And when they should fix here: is it better to move triaged bugs to this project in github and close the bugtracker in launchpad?

**Comment by Flohack74** [comment]
@toddy Thanks for your answer. We focus on Github for code & tickets, and we did yet not decide how to handle translations. Someone said its possible to hook up LP again or other 3rd party services, but this needs to be discussed.

So you are more than welcome to merge open pull requests from LP, and send them on here. Also, I can import different branches if this would be necessary (currently we imported only master).

If the bug can be closed immediately there is no need to transfer it here, but please start a changelog that we can apply to the releases. Bugs that remain open should be transferred however. We also do not have control over the LP bugttrackers, so we cant close them.

BR

**Comment by lkristensen** [comment]
I am prepared to maintain this package.
I have been developping CRM solutions and have a fairly good sense of CalDav and the like.

**Comment by Flohack74** [comment]
Cool! Currently we do not have a build chain for the core Apps, so you need to be a bit patient if you want to see changes appear in the various channels. Currently best practise is that you fork the project and send us pull requests.

BR

**Comment by Flohack74** [comment]
@toddy Meanwhile translations are set up at https://translate.ubports.com - I will add the calendar App there soon, then you can start contributing there =)

**Comment by lkristensen** [comment]
Cool. working on it now. What is the process for managing buglists? Should they be submitted here or on the fork?

**Comment by Flohack74** [comment]
Please put bugs here. The UBports team can triage and maintain, and if you are working on a bug leave a comment. Mention the bug in your PR and all is good... =). I close this now ;)
