### ISSUE TITLE
Enhancement time option

### ISSUE THREAD

**Issue by strangerer** [ubports/calendar-app#101]
Add options like
1) skip 1 month
 Edit: Jan,mar,may,... l.e 1,3,5,7,9,11
 (I don't know the actual term sorry)
2) include option when selecting month option in event i.e. 2nd wednesday of evey month

**Comment by hummlbach** [comment]
I'm not sure whether i understand the first... But i fully agree we should have the second. Can you please explain what you mean by the first?

**Comment by hummlbach** [comment]
keeping #146 instead

**Comment by strangerer** [comment]
Why the hell u closed my issue
