### ISSUE TITLE
Google calenders appear 12 times (each)

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/calendar-app#104]
device: hammerhead (Nexus 5)
version: 16.04 RC W32

What happens:
Since some time, all of my Google calendars appear 12 times in the list of calenders. I have more than 10 different Google calendars, so the list of calendars now has over 120 entries. This renders the selection dialog unusable.

What should happen:
Each Google calendar should appear only once in the list of calendars.

**Comment by ruedigerkupper** [comment]
![screenshot20180810_213126485](https://user-images.githubusercontent.com/21172886/43977621-f71cd5c8-9ce4-11e8-8cd1-75bb8c9f7506.png)

**Comment by ruedigerkupper** [comment]
In addition, there's one set of calendars that are all named like my Google account. These seem to be the "real ones": If I deselect all of the duplicates and just leave those, the calender and sync still works.

So, definitely, there's something broken with the sharing protocol.

**Comment by hummlbach** [comment]
Hi @ruedigerkupper! The duplicates arise out of beta testing (normally). The second is a bug and @mardy has already proposed a fix for it. For details on both please read this: https://github.com/ubports/ubuntu-touch/issues/762
