### ISSUE TITLE
Calendar app not syncing with Google calendar and wiping entries there

### ISSUE THREAD

**Issue by wagafo** [ubports/calendar-app#116]
Device: Nexus 5
    Channel: 16.04/rc
    Build: 2018-W35

Steps to reproduce

    Clean install 16.04/rc
    Enter Google calendar online account in Calendar app
    Sync with your Google calendar

Expected behavior

Calendar app and Google calendar should sync.
Actual behavior

    No entry of the Google calendar shows up in the Calendar app.
    After some attempts to sync, all entries with future dates in Google calendar were wiped out

See:
https://github.com/ubports/ubuntu-touch/issues/870
for some initial comments.

**Comment by mardy** [comment]
This is indeed most likely caused by the QtPim update. I'll investigate, but most likely the issue is not in the app, but rather in

**Comment by mardy** [comment]
The issue is probably in sync-monitor. I'll investigate :-)

**Comment by hummlbach** [comment]
Sound promising. Thanks a lot @mardy!

**Comment by hummlbach** [comment]
@mardy I this is not yet working (devel 18/09/23). Any other ideas?
