### ISSUE TITLE
Can't add nextcloud Calendar

### ISSUE THREAD

**Issue by userj** [ubports/calendar-app#117]
Device: Hammerhead, Fp2
Channel: 16.04/devel
Build: 2018-09-16

Tried adding Nextcloud calendar both from Calendar app and through Accounts. They both add the account to the system, but they do not sync and the calendar app keeps showing "add online calendar" instead of showing that the nextcloud calendar is there.

I get a sync notification, but nothing actually syncs.

**Comment by userj** [comment]
For some reason calendar is not synching now when using CalDav nor NC.
http://[mycloudaddress]/nextcloud/remote.php/dav/ 

The account will add but notification says "failed to sync ....."

**Comment by userj** [comment]
`syncevolution --print-databases`

Evolution Calendar = evolution-calendar:
   Birthdays & Anniversaries (birthdays)
   Contact birthdays (1537839152.21889.0@ubuntu-phablet)
   Personal (system-calendar) <default>
   Remote (1537839152.21889.1@ubuntu-phablet)
-------
However still fails to sync.

**Comment by hummlbach** [comment]
@userj this should now work again (on OTA5), please check.
