### ISSUE TITLE
Cannot switch default calendar

### ISSUE THREAD

**Issue by neopar** [ubports/calendar-app#129]
- BQ E5
- OTA-5 
- Calendar v 0.7.2

Steps to reproduce:
1. Add caldav account
2. Set it as default
3. Add another caldav account
4. Set the new one as defalt
5. Close settings
6. Open settings - default account is set the first one agian.

**Comment by hummlbach** [comment]
Confirmed.

**Comment by mardy** [comment]
Duplicate of ubports/ubuntu-touch#919
