### ISSUE TITLE
cannot change default calendar

### ISSUE THREAD

**Issue by a-i-m-a-r** [ubports/calendar-app#144]
I have several calendars that are show alfabetically. the default calendar is always the first one and cannot be changed. 
Although I change it in the settings, the change is not saved.

**Comment by hummlbach** [comment]
Thats already tracked here: https://github.com/ubports/ubuntu-touch/issues/919
Already fixed an will be released with OTA-6 I assume.

**Comment by mardy** [comment]
Please follow the issue linked by @hummlbach; I'm closing this :-)
