### ISSUE TITLE
pot file not updated

### ISSUE THREAD

**Issue by Danfro** [ubports/calendar-app#154]
I found so far two strings that are translatable in the qml file but do not show in weblate for translation:
Both in settings:
1. Display chinese calendar (that used to be "Show lunar calendar")
2. Business hours

-> the .pot file may need to be updated?

**Comment by hummlbach** [comment]
Yes you're i didn't update it. @Flohack74 what is good practice here? Committing the pot file whenever a release is made maybe?

**Comment by hummlbach** [comment]
Okay pot file has been commited (sorry for the delay...). I hope that is somehow find its way to the translation page...
