### ISSUE TITLE
Please add dark mode

### ISSUE THREAD

**Issue by thilovv** [ubports/calendar-app#156]
SuruDark works already good within the app. Would be great having the choice in the settings. Like in the Messaging App.

**Comment by hummlbach** [comment]
I think it makes more sense to have a global switch. Do you already know, theres a setting for the theme in ut tweak tool now?

**Comment by hummlbach** [comment]
Yes I would appreciate that and prefer to help 'fixing' those apps instead of introducing switches in the already theming compatible apps.

**Comment by bhdouglass** [comment]
I agree with @hummlbach there should be one global "dark mode" switch, rather than having every app implement their own version of it.

**Comment by thilovv** [comment]
Yes, SuruDark support should be enough.
