### ISSUE TITLE
Lunar Calendar

### ISSUE THREAD

**Issue by Gabriele69** [ubports/calendar-app#16]
This was an error already reported on Launchpad. If I point the box to show lunar calendars, a Chinese text appears, though the calendar app is localized in my language.

g

**Comment by advocatux** [comment]
Yes, that's an old issue from Canonical times. See:
https://bugs.launchpad.net/ubuntu-calendar-app/+bug/1607852
https://bugs.launchpad.net/ubuntu-calendar-app/+bug/1546800

When lunar calendar is activated, it gets its strings from here https://github.com/ubports/calendar-app/blob/master/qml/3rd-party/lunar.js

We need to find a way to translate those strings or maybe develop this alternative proposal https://bugs.launchpad.net/ubuntu-calendar-app/+bug/1546800/comments/5

**Comment by hummlbach** [comment]
Option "Show lunar calendar" is renamed to "Display chinese calendar" as it seems to be a little more than what the average western user would call a "lunar calendar". If really someone comes along who wants that in any other language he maybe also has the knowledge to translate it and is welcome to do it.
