### ISSUE TITLE
Cannot add internet calendar

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/calendar-app#21]
Since the first openstore release you can't add internet calendars any more.
Steps to reproduce: 
- In calendar-app, click the select-icon in upper right corner. 
- Click "add internet calendar"
- a dialog opens. This *used* to show "google" and "owncloud". However, since the last relase, it does show neither of these options and you can't select anything.

Deinstalling the openstore release and reinstalling previous version from the Ubuntu store fixes this problem.

**Comment by NeoTheThird** [comment]
Should be fixed in Sorry about that, should be fixed in 0.6.1. Please update to the latest version and check if the issue remains.

**Comment by V0ssi** [comment]
I still have the problem. 
When I click on "Add online Calendar" I get no options to choose.
I'm using Ubuntu 15.04. (r3) on a fairphone 2. The installed Calendar version is 0.6.2 .

If I click on the Ubuntu System Settings >> Account >> Google I can only activate the Accedd to Contacts but not to Calendar (see screenshot). 

![screenshot20180125_194109989](https://user-images.githubusercontent.com/35814671/35406419-23b31858-0209-11e8-9d57-48ac0d714c55.png)

**Comment by V0ssi** [comment]
Hi,
I flashed my phone again and it works now.

**Comment by timsueberkrueb** [comment]
Interesting, ran into the same thing.

**Comment by hummlbach** [comment]
While its working on my pro 5, I can confirm it with my nexus 4 (16.04).

**Comment by YougoCodes** [comment]
version 0.6.3 on my bq M10 HD 15.05/stable has this problem too. when choosing "add online calendar" a dialogue appears, titled "Online Accounts", with a description that says "choose an account", and one "cancel" button.

in system settings under accounts, calendar app is not listed to be permitted access

**Comment by brispete** [comment]
Same problem for me on my M10 FHD

**Comment by hummlbach** [comment]
YougoCodes findings':
- the same is happening for the notes app
- reflashing with wipe helps

While notes and calendar have this problem, the contacts app is not affected... What is different with the contacts  app? :)
