### ISSUE TITLE
Different colors for the dots in month view

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/calendar-app#28]
In the month view the calendar displays a dot in each day-box where there is an activity. It would be great to have that dot colored with the color associated with that calendar: for example this way I would know which days there are anniversaries and which days there are other events. I don't know what to suggest for days with both anniversaries and other events... maybe the current black dot?

**Comment by 3arn0wl** [comment]
I like the calendar app. I sometimes use it as a diary: when it's useful to have thoughts, notes etc. aligned to a date.

I've often thought that a ToDo function is an obvious Yang to the calendar Ying... if the devs are looking for things to do! ;)

**Comment by hummlbach** [comment]
Should the same be done for the indicator? ;)
