### ISSUE TITLE
Preset Time

### ISSUE THREAD

**Issue by Gabriele69** [ubports/calendar-app#3]
Hello,
This was a discussion I had already opened on Launchpad. 
In my opinion it would be useful to have preset times (15, 30, 45) when we insert new events on the calendar. 
Now we must necessarily run the minutes one by one.
It is, however, quite rare for me to have an appointment at 9.43 am. .... if we had a preset it would help to safeguard the safety of our finger ;-)!

**Comment by Flohack74** [comment]
Absolutely top suggestion :)

**Comment by lkristensen** [comment]
Looking at iOS they have 5 minute intervals. I thought that was a good compromise between granularity and list length.
