### ISSUE TITLE
Owncloud calendar - not working - FIX

### ISSUE THREAD

**Issue by ernesst** [ubports/calendar-app#30]
Following the non working calendar online-account for Owncloud/nextcloud, 

A patch was released to fix the missing header argument OCS-APIREQUEST: true
https://github.com/nextcloud/server/pull/2170

the patch is : 
http://launchpadlibrarian.net/310828133/account-plugins_0.13+17.04.20161206-0ubuntu1_0.13+17.04.20170314-0ubuntu1.diff.gz

Would it be possible to implement it to re-enable the online account feature ? 

Sorry if it's not the relevant place, couldn't find the online-account ubport github.

**Comment by Flohack74** [comment]
@mardy Can you make a PR for that?

**Comment by mardy** [comment]
Sure, please import the account-plugins repository into the ubports organization. I believe you can just clone my repo here:
   https://github.com/mardy/account-plugins

The patch is already in that repo, so there's no need for a PR: just clone the repo and make a new build out of it.

**Comment by Flohack74** [comment]
Hmm shouldn´t we use https://github.com/ubports/account-polld-plugins-go now?

**Comment by mardy** [comment]
Those are the plugins for account-polld; here we are talking about the plugins for ubuntu-system-settings-online-accounts, that is those responsible for the account creation.

**Comment by Flohack74** [comment]
Uhhh shame on me! Yes ok we can fork that one ;)

**Comment by ernesst** [comment]
@mardy, i've some question on how to use ubuntu touch online account 2.0, where can i expose my problem ? 
I'm trying to develop an app on Utouch to connect to owncloud/nextcloud bookmark app. thanks

@Flohack74, Any update on the fork ?

**Comment by mardy** [comment]
@ernesst I started working on such an app some time ago: https://gitlab.com/mardy/owncloud-bookmarks
I don't have time to push it forward now, so feel free to fork the code.
For questions, I would suggest using the ubuntu-phone mailing list :-)

**Comment by Flohack74** [comment]
Repo is forked now, and I will try to hook up Jenkins to it...

**Comment by ernesst** [comment]
fix present in each file cloud provider : 
https://github.com/ubports/account-plugins/blob/master/qml/owncloud/NewAccount.qml
https://github.com/ubports/account-plugins/blob/master/qml/nextcloud/NewAccount.qml

Need to build it and include in ubport ^^

Thanks
