### ISSUE TITLE
Day view to scroll to first event of day

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/calendar-app#35]
When I swipe the days of the week on my calendar or when I open the calendar in day view I can miss seeing events due to the fact that the whole day does not fit on the screen. In order not to miss events I should sweep first to the next day and then sweep up and down to see the whole day. Could it be made that if there is an event planned on that day the calendar will scroll to that specific event?

**Comment by lkristensen** [comment]
Currently it scrolls to current time, on the request of another user. Maybe this could be added as an option.

**Comment by mihaelmilea** [comment]
I agree, that is good. But what about swiping through the days of the week?

**Comment by hummlbach** [comment]
Actually for me it currently scrolls nowhere... Can someone please confirm this? (Perhaps the needs confirmation label was not that bad... ;))

**Comment by hummlbach** [comment]
Ah, on startup, it scrolls to current time.

**Comment by hummlbach** [comment]
I'm imagining the view jumping forth and back while swiping through the high noons just looking for a free affaire d'honneur slot... Driving me insane... And what should happen if there was an event in the morning as well as in the evening? Zooming out? So we could eventually have an option 'ensure all events are shown'. Then we would have to clarify how it is ensured exactly: Lets say working hours are displayed and the only event that day is at 8 pm - scrolling or zooming or both?

**Comment by hummlbach** [comment]
Closed for the same reason as #4. If someone wanted to implement it, it would have to be optionally. Take into account the previous comment.
