### ISSUE TITLE
Wrong day for a whole day event in Date & Time indicator

### ISSUE THREAD

**Issue by zlamalp** [ubports/calendar-app#37]
I have an event set for a whole day on 16th of October 2017. In calendar app it's displayed correctly on "Monday" but in indicator it's displayed as "event Sun 00:00". If I disable "whole day" and set it to 00:00-23:55 its displayed correctly as "event Mon 00:00". I'm posting it here, since indicator-datetime has issues disabled.

**Comment by GermoVeltmaat** [comment]
My whole day events get show at 23:00 the day before.
We just changed back from daylight-saving-time. Could be that it started then ;-)

**Comment by hummlbach** [comment]
Closing this since its an duplicate of #88.
