### ISSUE TITLE
Titles and dates in wrong language

### ISSUE THREAD

**Issue by GermoVeltmaat** [ubports/calendar-app#38]
I see titles and numbers in foreign language.

![screenshot20171014_155900805](https://user-images.githubusercontent.com/32248795/31576424-c3403a6e-b0fa-11e7-8f56-398f77d729ab.png)

**Comment by GermoVeltmaat** [comment]
Reinstalled the app and now all is well

**Comment by NeoTheThird** [comment]
Thanks for reporting. Is it possible that you enabled lunar calendar? See #16

**Comment by GermoVeltmaat** [comment]
Yes. You are right.
I guess i won't be using the lunar calendar until it is resolved ;-)
