### ISSUE TITLE
Day view on screen should show working hours by default

### ISSUE THREAD

**Issue by bastos77** [ubports/calendar-app#4]
It would be helpful to see the working hours (e.g 8am to 6pm) by default on the screen when activating day view or even week view.
Currently the day view starts at 0.00 so the working hours with the entries are not visible on first view.

**Comment by Gabriele69** [comment]
Yes. And it would be helpful have a different background color for working hours.

G

**Comment by lkristensen** [comment]
I have moved the background color to a separate issue, as these will have to be solved individually

**Comment by hummlbach** [comment]
@NeoTheThird actually I would see this as an enhancement not as bugbug(?)

**Comment by hummlbach** [comment]
So the request is to scroll to 8 am automatically? But to the current time for the current day?
Why is this a bug and not an improvement?

**Comment by hummlbach** [comment]
So the request is to scroll to 8 am automatically? But to the current time for the current day?
Why is this a bug and not an improvement?

**Comment by hummlbach** [comment]
@bastos77 would it be sufficient if the calendar was remembering how the view was scrolled/zoomed lastly?

**Comment by bastos77** [comment]
At my FP2 rc22 this issue is obsolete for me because I am happy how it has been solved. When going to day view I see by default 7am to 2pm.

One (small) improvement aspect if I may: Would be great to see 7am to 6pm on the default screen. In my opinion there would be enough space for every hour to at least show the headline of an entry

**Comment by hummlbach** [comment]
The behavior I observe is scrolling to the current time on startup and remembering the scroll state afterwards. Actually not what you describe. Does it really behave different for you? If you're fine with this, I will label this as wont fix. (remembering the last state is a good idea in my opinion too)
