### ISSUE TITLE
Links in README

### ISSUE THREAD

**Issue by nikita-veshchikov** [ubports/calendar-app#43]
The Useful links in the README file are not useful, the first two point to a 404 page on the  ubuntu web-site:

Home Page      - https://developer.ubuntu.com/en/community/core-apps/calendar/
Calendar App Wiki - https://wiki.ubuntu.com/Touch/CoreApps/Calendar

I've tried to find the correct links but did not succeed (e.g., nothing in the ubport wiki).

**Comment by NeoTheThird** [comment]
https://github.com/ubports/calendar-app/commit/91d1073de3ce037b69171b398ffe24ebf64f85b3 fixed
