### ISSUE TITLE
Tapping on the space to the left of the checkmark in Calendar's settings should toggle the checkbox

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/calendar-app#55]
_From @tsimonq2 on March 4, 2018 1:35_

- Device: hammerhead
- Channel: xenial/devel
- Build: r279

### Steps to reproduce
Open the Calendar app and navigate to the settings. Try to check/uncheck any of the buttons.

### Expected behavior
You have to tap _right on the checkmark_ for it to be toggled.

### Actual behavior
I should be able to tap anywhere on that line and it should toggle.

_Copied from original issue: ubports/ubuntu-touch#506_

**Comment by dobey** [comment]
This is a trivial fix. Will submit a PR shortly.
