### ISSUE TITLE
In Calendar, tapping on the default calendar to select makes that whole part of the menu disappear

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/calendar-app#56]
_From @tsimonq2 on March 4, 2018 1:32_

- Device: hammerhead
- Channel: xenial/devel
- Build: r279

### Steps to reproduce
Open the Calendar app and go to Settings. Try to set a default calendar other than the one you have selected.

### Actual behavior
The whole "Default calendar" part of the menu just goes away. Only after restarting the app does it show up again.

_Copied from original issue: ubports/ubuntu-touch#505_

**Comment by hummlbach** [comment]
Is this really device dependent? Because I don't see this on my meizu pro 5...

**Comment by hummlbach** [comment]
I'm not able to reproduce that. Neither on 15.04 nor on 16.04. Neither on mako nor on turbo and also not on the laptop.

**Comment by hummlbach** [comment]
I cannot reproduce this and there seems to be none complaining anymore -> closed
