### ISSUE TITLE
Add additional frequencies for events in calendar 

### ISSUE THREAD

**Issue by Flohack74** [ubports/calendar-app#6]
_From @fbremond on July 17, 2017 18:25_

In calendar we can add events which repeat every week or every month but I need to add events which repeat every two weeks or 4 weeks.
Is it possible to add this feature?
Thanks

_Copied from original issue: ubports/ubports-touch#166_

**Comment by nikita-veshchikov** [comment]
That would be one of the best enhancements for the calendar.
I have a lot of events that appear only every 2 or every 6 weeks or every 3 month for example.

**Comment by hummlbach** [comment]
That was an easy one... :)
Took me only half an hour. The used QML RecurrenceRule element already provides everything needed. Uh, needs to be translated...

**Comment by hummlbach** [comment]
Implemented
