### ISSUE TITLE
New event dialogue called from month/year view does not suggest default calendar

### ISSUE THREAD

**Issue by hummlbach** [ubports/calendar-app#64]
Reproduction: Long tap on a date in month or year view to open the new event dialogue.

What happens: New event dialogue pops up, but the suggested/preselected calendar is not the default calendar but the first in the list.

What was expected: I assume, the expcted behavior would be to preselect the default calendar as it happens if the new event dialogue is called from day or week view.

**Comment by userj** [comment]
I noticed this too. Even if you go to the settings to select a default calendar, there is no way to 'save' the setting. When you exit settings, it reverts default back to the first calendar in the list.

**Comment by Ingo-FP-Angel** [comment]
I updated from devel (625) to rc (24; 2018-W48) on FP2 and still have the problem that I cannot set a default calendar.

When I select a default calendar that's not the first in the list, this setting is not persisted. After selecting the second entry, when I go back to the calendar view and open the settings again, the default calendar is reverted to the first in the list.

**Comment by hummlbach** [comment]
Have you used the 0.8.0-beta of the calendar app?

**Comment by Ingo-FP-Angel** [comment]
No, it is 0.7.2. That is the version I have after changing to RC/installing updates from the open store.
I assumed that was what is supposed to be tested in the call for testing.
But I can try with 0.8.0-beta

**Comment by userj** [comment]
Still have this issue in OTA-6 as of today.
