### ISSUE TITLE
Removal of Birthdays and Anniversaries calendar option? [feature removal]

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/calendar-app#75]
It could be that more than one of us do not understand the usage or original idea behind this 'birthdays and anniversaries' calendar option on the default list in calendar choices.  The following french screenshot shows it (top position in green square).  

It seems that it also does not work correctly and when you create a new event you cannot add the event to this 'birthdays and anniversaries' calendar.  

Our suggestion is that it could be removed and people could put their birthday, holiday, anniversaries directly on their own calendars or import them from online sources

![add_calendar_page](https://user-images.githubusercontent.com/16578346/39308492-6f3233ba-491a-11e8-8b27-fce2e49c4399.jpg)

**Comment by dobey** [comment]
No, it should not be removed. It is a read-only special option via evolution-data-server which shows the birthdays and anniversaries from your Contacts, in your calendar, if you choose. You can choose visibility in the calendar, but you cannot select it as a source to write to. It works the same way in Evolution and GNOME Calendar on PC too.

**Comment by wayneoutthere** [comment]
Did not know that.  Very cool.  Close this ticket and start new ticket called 'need user manuals' ;)

**Comment by hummlbach** [comment]
Does that mean that you're able to give your contacts a birthday? For some reason, my contacts do not provide me with a field for the birthday...

**Comment by wayneoutthere** [comment]
you are right... the birthday option is not in that drop down of add-able fields in contacts when you make a new contact.  weird.  i guess maybe it used to be there.... it should be there.  It makes sense for sure and is actually pretty great idea to have it linked to contacts.

**Comment by hummlbach** [comment]
There's actually an issue for that in the contacts app: https://github.com/ubports/address-book-app/issues/5. I'm wondering if it really was never there, but it seems so. I'm also not sure if it would agree with POLA to have it there... ;)

**Comment by dobey** [comment]
The UI should be implemented in contacts app. I guess it's never been there. AFAIK, there's no good reason for it not being there. It just never got implemented.
