### ISSUE TITLE
V. 0.7.1 not present in 15.04 RC15 

### ISSUE THREAD

**Issue by Gabriele69** [ubports/calendar-app#80]
Hi, I've BQe4.5 phone with Ubports RC r15. My Openstore not show this release. The current release is 0.6.3

**Comment by hummlbach** [comment]
Its not yet 'released'. Not yet pushed to the openstore. The click packages on github are for testing purposes and therefor there before the versions appear in the openstore.

**Comment by Flohack74** [comment]
Closing this...
