### ISSUE TITLE
Times not respecting my locale

### ISSUE THREAD

**Issue by bhdouglass** [ubports/calendar-app#81]
I have my locale set to English/US in the system settings. I would expect that the calendar show times in am/pm in the calendar view, but instead it shows 24 hour time (14:30 vs 2:30pm). This is true for both the week and day views, but the agenda view gets it correct. Also, it does show am/pm when creating/editing an event, but when editing the time it shows 24 hour time again for the time picker.

So the week view, day view, and time picker should be updated to respect the locale.

**Comment by hummlbach** [comment]
This would have an very easy (two lined fix) if the time scale column hadn't a fixed size at the moment. So this will need a little bit of refactoring before it can be fixed properly.

**Comment by hummlbach** [comment]
Created https://github.com/ubports/calendar-app/issues/105 as reminder for doing the hard part later.
