### ISSUE TITLE
[xenial] Unable to allow access to Google account

### ISSUE THREAD

**Issue by zubozrout** [ubports/calendar-app#89]
Hello,
I am unable to use Google calendar with Calendar app on Xenial. That is there is no way I can allow the app access to Google account. In system settings only Contacts app is listed under my Google account but Calendar app is missing.

Could this perhaps be a similar issue to Telegram not being able to use Ubuntu account?
https://github.com/ubports/telegram-app/issues/174

Thank you very much.

I am on Ubuntu 16.04 r85, Meizu MX4 (arale)

**Comment by tudorels** [comment]
I have the same issue with a turbo device on r89.

**Comment by Flohack74** [comment]
Please check https://github.com/ubports/ubuntu-touch first, it sounds like a duplicate of something that was reported there. In general, all elements that are not in the App itself, should be reported against ubuntu-touch.

**Comment by zubozrout** [comment]
@Flohack74 The problem is I can see one app in online accounts so thought this may be app specific. But should have checked first. This is most probably a duplicate of this: https://github.com/ubports/ubuntu-touch/issues/589 so closing this ticket.
