### ISSUE TITLE
Two-way sync with cloud provider

### ISSUE THREAD

**Issue by Amolith** [ubports/calendar-app#92]
I don't know if I'm simply missing something or what but events that I create on UT are not synced to my cloud calendar application. Events I create in the cloud application are synced to UT but not the other way around and this is something that is essential IMO.

I'm on 15.04 hammerhead in case this is a bug.

**Comment by hummlbach** [comment]
Can you please provide a little more detail? What kind of account do you use? It is working for me in both directions with caldav.

**Comment by Amolith** [comment]
It was an issue with my account that I didn't catch until I checked it. Somehow, the option to use the Google account was disabled and I was adding all my events to that account. When I tried to re-enable it, it said that the token was no longer valid so I had to remove the account then re-add it. Now, all the events I've created for the past few weeks are gone but they are syncing now, so that's good.
