### ISSUE TITLE
More comprehensive Repeat settings

### ISSUE THREAD

**Issue by Amolith** [ubports/calendar-app#97]
I'm trying to schedule my classes for next semester and both of the ones that meet on-campus are Monday/Wednesday classes but the only repeat option that would closely fit Mon, Wed, Fri. I know I can make two separate events that repeat weekly and that'll do for now but it would be more efficient to have that option in the settings.

Something like this (but with UT UI :wink:) would be perfect:
![](https://2.bp.blogspot.com/-JcYLZTVQt1I/UaihHpqTgAI/AAAAAAABJrU/ClkTwNHAxz4/s640/android-calendar-repeat.png)

**Comment by Amolith** [comment]
I would delete the issue but I don't see an option. I'm just gonna close it . . . :sweat_smile:

**Comment by hummlbach** [comment]
Yes this feature exists. Nonetheless there is some room for improvements obv... :) what I'm missing is an option to say every second Monday in an month for example.
